
import javax.swing.JButton;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author sebas
 */
public class Formulario_2 extends javax.swing.JPanel {

  /**
   * Creates new form Formulario_2
   */
  public Formulario_2() {
    initComponents();
  }

  public JButton getBtn_ok() {
    return btn_ok;
  }

  public JTextField getTxtfld_apellido() {
    return txtfld_apellido;
  }

  public JTextField getTxtfld_nombre() {
    return txtfld_nombre;
  }

  
  
  
  
  
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton2 = new javax.swing.JButton();
    lbl_nombre = new javax.swing.JLabel();
    lbl_apellido = new javax.swing.JLabel();
    txtfld_nombre = new javax.swing.JTextField();
    txtfld_apellido = new javax.swing.JTextField();
    btn_ok = new javax.swing.JButton();

    setBackground(new java.awt.Color(255, 255, 102));

    jButton2.setText("jButton2");

    lbl_nombre.setText("nombre");

    lbl_apellido.setText("apellido");

    btn_ok.setText("ok");
    btn_ok.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_okActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(68, 68, 68)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addComponent(lbl_nombre)
            .addGap(18, 18, 18)
            .addComponent(txtfld_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lbl_apellido)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                .addComponent(btn_ok)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2))
              .addComponent(txtfld_apellido))))
        .addContainerGap(72, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(51, 51, 51)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_nombre)
          .addComponent(txtfld_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(lbl_apellido)
          .addComponent(txtfld_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(61, 61, 61)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btn_ok)
          .addComponent(jButton2))
        .addContainerGap(104, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
    // TODO add your handling code here:
    
    
    
    
    
  }//GEN-LAST:event_btn_okActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_ok;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel lbl_apellido;
  private javax.swing.JLabel lbl_nombre;
  private javax.swing.JTextField txtfld_apellido;
  private javax.swing.JTextField txtfld_nombre;
  // End of variables declaration//GEN-END:variables
}
