
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sebas
 */
public class Sinc extends javax.swing.JFrame {

  /**
   * Creates new form Sinc
   */
  public Sinc() {
    initComponents();
    
    
  }

      int valor = 0;
    
    public synchronized void modificar(int hilo, int tiempo){
      if(hilo == 0)
        txt_areaA.append("A: valor inicial = " + valor + "\n"); 
      else
        txt_areaB.append("B: valor inicial = " + valor + "\n");
      
      valor++;
      
    try {
      Thread.sleep(tiempo);
    } catch (InterruptedException ex) {
      Logger.getLogger(Sinc.class.getName()).log(Level.SEVERE, null, ex);
    }
              
      if(hilo == 0)
        txt_areaA.append("A: valor final = " + valor + "\n"); 
      else
        txt_areaB.append("B: valor final = " + valor + "\n");
      
      
    }
  
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lbl_hiloA = new javax.swing.JLabel();
    lbl_hiloB = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    txt_areaA = new javax.swing.JTextArea();
    jScrollPane2 = new javax.swing.JScrollPane();
    txt_areaB = new javax.swing.JTextArea();
    btn_start = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    lbl_hiloA.setText("hilo A");

    lbl_hiloB.setText("hilo B");

    txt_areaA.setColumns(20);
    txt_areaA.setRows(5);
    jScrollPane1.setViewportView(txt_areaA);

    txt_areaB.setColumns(20);
    txt_areaB.setRows(5);
    jScrollPane2.setViewportView(txt_areaB);

    btn_start.setText("start");
    btn_start.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btn_startMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(lbl_hiloA)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_hiloB)))
        .addContainerGap())
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btn_start)
        .addGap(185, 185, 185))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(lbl_hiloB)
          .addComponent(lbl_hiloA, javax.swing.GroupLayout.Alignment.TRAILING))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
          .addComponent(jScrollPane2))
        .addGap(18, 18, 18)
        .addComponent(btn_start)
        .addContainerGap(27, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btn_startMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_startMouseClicked
    // TODO add your handling code here:
    
    
    Runnable runA = new Runnable(){
      @Override
      public void run() {
        for (int i = 0; i < 10; i++) {
          modificar(0,400);
          
        }
        
        
      }
      
    };

    
    Runnable runB = new Runnable(){
      @Override
      public void run() {
        for (int i = 0; i < 10; i++) {
          modificar(1,500);
        }
        
      }
      
    };    
    
    
    Thread hiloA = new Thread(runA);
    hiloA.start();
    Thread hiloB = new Thread(runB);
    hiloB.start();
    
    
  }//GEN-LAST:event_btn_startMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Sinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Sinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Sinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Sinc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Sinc().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_start;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JLabel lbl_hiloA;
  private javax.swing.JLabel lbl_hiloB;
  private javax.swing.JTextArea txt_areaA;
  private javax.swing.JTextArea txt_areaB;
  // End of variables declaration//GEN-END:variables
}
