
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.nio.file.Files;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sebas
 */
public class BlockNotas extends javax.swing.JFrame {

  /**
   * Creates new form BlockNotas
   */
  public BlockNotas() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    btnsave = new javax.swing.JButton();
    btnopen = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    txta1 = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    btnsave.setText("save");
    btnsave.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnsaveMouseClicked(evt);
      }
    });

    btnopen.setText("open");
    btnopen.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnopenMouseClicked(evt);
      }
    });

    txta1.setColumns(20);
    txta1.setRows(5);
    jScrollPane1.setViewportView(txta1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnopen)
          .addComponent(btnsave))
        .addGap(31, 31, 31))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(44, 44, 44)
            .addComponent(btnopen)
            .addGap(31, 31, 31)
            .addComponent(btnsave))
          .addGroup(layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(65, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnopenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnopenMouseClicked
    // TODO add your handling code here:
    JFileChooser jfcopendoc = new JFileChooser("C:\\Users\\sebas\\Desktop\\TAP_1");
      int resu = jfcopendoc.showOpenDialog(this);
      if(resu == JFileChooser.APPROVE_OPTION){
      System.out.println(jfcopendoc.getSelectedFile());
      BufferedReader br = null;
      InputStream is = null;
      
      try{
//se necesita reader para pasar a textarea

      is = Files.newInputStream(jfcopendoc.getSelectedFile().toPath()) ;
      InputStreamReader isr = new InputStreamReader(is);
      br = new BufferedReader(isr);
      txta1.read(br, "abrir archivo");
  }catch (IOException ex) {
    ex.printStackTrace();
  }finally{
        try{
        if(br!=null){
        is.close();
        br.close();
        }
        }catch(IOException ex){
             ex.printStackTrace();
        }
      }
    }
  
          
  }//GEN-LAST:event_btnopenMouseClicked

  private void btnsaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsaveMouseClicked
    // TODO add your handling code here:
    JFileChooser jfcsavedoc = new JFileChooser("C:\\Users\\sebas\\Desktop\\TAP_1");
      int resu = jfcsavedoc.showOpenDialog(this);
      if(resu == JFileChooser.APPROVE_OPTION){
        BufferedWriter br = null;
        OutputStream is = null;
        
        try{
          is = Files.newOutputStream(jfcsavedoc.getSelectedFile().toPath());
          OutputStreamWriter ow = new OutputStreamWriter(is);
          br = new BufferedWriter(ow);
          txta1.write(br);
          
        }catch(IOException ex){
          ex.printStackTrace();
        }finally{
        try{
        if(br!=null){
        is.close();
        br.close();
        }
        }catch(IOException ex){
             ex.printStackTrace();
        }
      }
        
        
        
      }
    
  }//GEN-LAST:event_btnsaveMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(BlockNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(BlockNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(BlockNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(BlockNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new BlockNotas().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnopen;
  private javax.swing.JButton btnsave;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea txta1;
  // End of variables declaration//GEN-END:variables
}
